backend:
  name: git-gateway
  branch: master

media_folder: source/images/
public_folder: /images/

site_url: https://waldlicht.netlify.com
display_url: https://waldlicht.netlify.com

collections:
  - label: "Abschnitte der Seite"
    name: "sections"
    files:
      - label: "Intro"
        name: "intro"
        file: "/source/main/01_top.html.md"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Untertitel", name: "subtitle", widget: "string", required: false }
          - { label: "Text", name: "body", widget: "markdown" }
          - { label: "Flyer", name: "flyer_url", widget: file, allow_multiple: false }
          - { label: "Bild", name: "image", widget: image, required: false}
      - label: "Philosophie"
        name: "philosophie"
        file: "/source/main/02_philosophie.html.md"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Untertitel", name: "subtitle", widget: "string", required: false }
          - { label: "Text", name: "body", widget: "markdown", required: false }
          - label: "Aufzählungspunkte"
            name: "bullets"
            widget: "list"
            fields:
              - label: "Aufzählungspunkt"
                name: "bullet"
                widget: "string"
          - { label: "Bild", name: "image", widget: image, required: false}
      - label: "Tagesablauf"
        name: "tagesablauf"
        file: "/source/main/03_tagesablauf.html.md"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Untertitel", name: "subtitle", widget: "string", required: false }
          - { label: "Zeitslotsüberschrift", name: "time_slots_header", widget: "string" }
          - label: "Zeitslots"
            name: "time_slots"
            widget: "list"
            fields:
              - label: "Zeitspanne"
                name: "time_frame"
                widget: "string"
              - label: "Beschreibung"
                name: "description"
                widget: "string"
          - { label: "Text", name: "body", widget: "markdown" }
          - { label: "Bild", name: "image", widget: image, required: false}
      - label: "Das Team"
        name: "team"
        file: "/source/main/04_team.html.md"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Untertitel", name: "subtitle", widget: "string", required: false }
          - { label: "Text", name: "body", widget: "markdown" }
          - label: "Mitglieder"
            name: "members"
            widget: "list"
            fields:
              - label: "Name"
                name: "name"
                widget: "string"
              - label: "Beschreibung"
                name: "description"
                widget: "string"
          - { label: "Bild", name: "image", widget: image, required: false}
      - label: "Sponsoren"
        name: "sponsors"
        file: "/source/main/07_sponsoren.html.md"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Untertitel", name: "subtitle", widget: "string", required: false }
          - { label: "Text", name: "body", widget: "markdown" }
          - label: "Sponsoren"
            name: "sponsors"
            widget: "list"
            fields:
              - label: "Name"
                name: "name"
                widget: "string"
              - label: "Beschreibung"
                name: "description"
                widget: "string"
              - label: "Logo"
                name: "logo"
                widget: "image"
                required: false
          - { label: "Bild", name: "image", widget: image, required: false}
      - label: "Galerie"
        name: "gallery"
        file: "/source/main/05_gallery.html.md"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Untertitel", name: "subtitle", widget: "string", required: false }
          - { label: "Video URL", name: "video_url", widget: "string" }
          - { label: "Text", name: "body", widget: "markdown" }
          - label: "Bilder"
            name: "gallery_images"
            widget: "list"
            field: { label: Bild, name: image, widget: image }
      - label: "Standort"
        name: "Standort"
        file: "/source/main/06_anfahrt.html.md"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Untertitel", name: "subtitle", widget: "string", required: false }
          - { label: "Text", name: "body", widget: "markdown", required: false }
          - { label: "URL für Kartenwidget", name: iframe_map_url, widget: string}
          - { label: "URL für große Karte", name: link_map_url, widget: string}
 