backend:
  name: git-gateway
  branch: master

media_folder: source/images/uploads
public_folder: /images/uploads

site_url: https://waldlicht.netlify.com
display_url: https://waldlicht.netlify.com

collections:
  - label: "Abschnitte"
    name: "sections"
    files:
      - label: "Intro"
        name: "intro"
        file: "/source/main/01_top.html.md"
        fields:
          - { label: "Layout", name: "layout", widget: "hidden", default: "null" }
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Untertitel", name: "subtitle", widget: "string" }
          - { label: "Body", name: "body", widget: "text" }
      - label: "Philosophie"
        name: "philosophie"
        file: "/source/main/02_philosophie.html.md"
        fields:
          - { label: "Layout", name: "layout", widget: "hidden", default: "null" }
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Untertitel", name: "subtitle", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "Aufzählungspunkte"
            name: "bullets"
            widget: "list"
            fields:
              - label: "Aufzählungspunkt"
                name: "bullet"
                widget: "string"
      - label: "Tagesablauf"
        name: "tagesablauf"
        file: "/source/main/03_tagesablauf.html.md"
        fields:
          - { label: "Layout", name: "layout", widget: "hidden", default: "null" }
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Untertitel", name: "subtitle", widget: "string" }
          - { label: "Zeitslotsüberschrift", name: "time_slots_header", widget: "string" }
          - label: "Zeitslots"
            name: "time_slots"
            widget: "list"
            fields:
              - label: "Zeitspanne"
                name: "time_frame"
                widget: "string"
              - label: "Beschreibung"
                name: "description"
                widget: "string"
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Das Team"
        name: "team"
        file: "/source/main/04_team.html.md"
        fields:
          - { label: "Layout", name: "layout", widget: "hidden", default: "null" }
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Untertitel", name: "subtitle", widget: "string" }
          - { label: "Body", name: "body", widget: "text" }
          - label: "Mitglieder"
            name: "members"
            widget: "list"
            fields:
              - label: "Name"
                name: "name"
                widget: "string"
              - label: "Beschreibung"
                name: "description"
                widget: "string"

  - label: "Pages"
    name: "pages"
    files:
      - label: "Elements"
        name: "elements"
        file: "/source/elements.html"
        fields:
          - {label: "Body", name: "body", widget: "text"}

