backend:
  name: git-gateway
  branch: master

media_folder: source/images/uploads
public_folder: /images/uploads

site_url: https://waldlicht.netlify.com
display_url: https://waldlicht.netlify.com

collections:
  - label: "Hauptseite"
    name: "main"
    files:
      - label: "Abschnitte"
        name: "main_page_sections"
        file: "/source/main_page.html.md"
        fields:
          - label: "Abschnitte"
            name: "sections"
            widget: "list"
            fields:
              - label: "Abschnitt"
                name: "section"
                collection: "sections"
                searchFields: "title"
                valueField: "title"
  - label: "Abschnitte"
    name: "sections"
    folder: "/source/main"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Untertitel", name: "subtitle", widget: "string" }
      - { label: "Text", name: "body", widget: "text" }
  - label: "Pages"
    name: "pages"
    files:
      - label: "Elements"
        name: "elements"
        file: "/source/elements.html"
        fields:
          - {label: "Body", name: "body", widget: "text"}

